name: 'Github Wiki notifications for Teams'
author: 'Jakub Duchon'
description: 'Take a payload of gollum (Github wiki) event and send a formatted notification to a specified Microsoft Teams channel.'
runs:
  using: 'node12'
  main: './src/index.js'
branding:
  color: 'blue'
  icon: 'alert-circle'
